"""Entity Definitions."""

ENTITY_DEFINITIONS = {
    "sensor": {
        "anlagenzustand": {
            "register": 34001,
            "type": "text",
            "translation_key": "anlagenzustand",
        },
        "kesselzustand": {
            "register": 34002,
            "type": "text",
            "translation_key": "kesselzustand",
        },
        "aussentemperatur": {
            "register": 31001,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "stunden_im_pelletsbetrieb": {
            "register": 30063,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "stunden_im_heizen": {
            "register": 30064,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "stunden_im_scheitholzbetrieb": {
            "register": 30077,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
    },
    "kessel": {
        "kesseltemperatur": {
            "register": 30001,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "abgastemperatur": {
            "register": 30002,
            "unit": "°C",
            "scaling": 1,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "verbleibende_heizstunden_bis_zur_asche_entleeren_warnung": {
            "register": 30087,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "saugzug_ansteuerung": {
            "register": 30014,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "saugzugdrehzahl": {
            "register": 30007,
            "unit": "upm",
            "scaling": 1,
            "type": "sensor",
        },
        "sauerstoffregler": {
            "register": 30017,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "restsauerstoffgehalt": {
            "register": 30004,
            "unit": "%",
            "scaling": 10,
            "decimals": 1,
            "type": "sensor",
        },
        "ruecklauffuehler": {
            "register": 30010,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "primaerluft": {
            "register": 30012,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "sekundaerluft": {
            "register": 30013,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "betriebsstunden": {
            "register": 30021,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "stunden_seit_letzter_wartung": {
            "register": 30056,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "betriebsstunden_in_der_feuererhaltung": {
            "register": 30025,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "kessel_solltemperatur": {
            "register": 40001,
            "unit": "°C",
            "scaling": 2,
            "min": 70,
            "max": 90,
            "type": "number",
        },
        "bei_welcher_rl_temperatur_an_der_zirkulationsleitung_soll_die_pumpe_ausschalten": {
            "register": 40601,
            "unit": "°C",
            "scaling": 2,
            "min": 20,
            "max": 120,
            "type": "number",
        },
    },
    "fehlerpuffer": {
        f"kessel_fehlerpuffer_{i + 1}": {
            "register": 33001 + i,
            "type": "text",
            "translation_key": "kessel_fehler",
        }
        for i in range(20)
    },
    "boiler01": {
        "boiler_1_temperatur_oben": {
            "register": 31631,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "boiler_1_pumpe_ansteuerung": {
            "register": 31633,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "boiler_1_pumpe_an_aus": {
            "register": 31633,
            "type": "binary_sensor_from_register",
        },
        "boiler_1_gewuenschte_boilertemperatur": {
            "register": 41632,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 100,
            "type": "number",
        },
        "boiler_1_nachladen_wenn_boilertemperatur_unter": {
            "register": 41633,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
        },
        "boiler_1_solltemperatur_externe_vorgabe": {
            "register": 48019,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
        },
    },
    "boiler02": {
        "boiler_2_temperatur_oben": {
            "register": 31661,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "boiler_2_pumpe_ansteuerung": {
            "register": 31663,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "boiler_2_pumpe_an_aus": {
            "register": 31663,
            "type": "binary_sensor_from_register",
        },
        "boiler_2_gewuenschte_boilertemperatur": {
            "register": 41662,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 100,
            "type": "number",
        },
        "boiler_2_nachladen_wenn_boilertemperatur_unter": {
            "register": 41663,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
        },
    },
    "hk1": {
        "hk1_vorlauf_isttemperatur": {
            "register": 31031,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk1_vorlauf_solltemperatur": {
            "register": 31032,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk1_raumtemperatur": {
            "register": 31033,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk1_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41036,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk1_vorlauf_temperatur_externe_vorgabe": {
            "register": 48001,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
        },
        "hk1_pumpe_an_aus": {"coil": 1030, "type": "binary_sensor"},
        "hk1_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41032,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk1_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41033,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk1_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41040,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk1_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41034,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
        },
        "hk1_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41037,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk1_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41038,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk1_frostschutztemperatur": {
            "register": 41039,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 20,
            "type": "number",
        },
        "hk1_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41048,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
        },
        "hk1_betriebsart": {
            "register": 48047,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk1_freigabe_externe_vorgabe": {
            "register": 48029,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk2": {
        "hk2_vorlauf_isttemperatur": {
            "register": 31061,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk2_vorlauf_solltemperatur": {
            "register": 31062,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk2_raumtemperatur": {
            "register": 31063,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk2_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41066,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk2_vorlauf_temperatur_externe_vorgabe": {
            "register": 48002,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
        },
        "hk2_pumpe_an_aus": {"coil": 1060, "type": "binary_sensor"},
        "hk2_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41062,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk2_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41063,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk2_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41070,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk2_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41064,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
        },
        "hk2_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41067,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk2_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41068,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk2_frostschutztemperatur": {
            "register": 41069,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
        },
        "hk2_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41079,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
        },
        "hk2_betriebsart": {
            "register": 48048,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk2_freigabe_externe_vorgabe": {
            "register": 48030,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk3": {
        "hk3_vorlauf_isttemperatur": {
            "register": 31091,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk3_vorlauf_solltemperatur": {
            "register": 31092,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk3_raumtemperatur": {
            "register": 31093,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk3_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41096,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk3_vorlauf_temperatur_externe_vorgabe": {
            "register": 48003,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
        },
        "hk3_pumpe_an_aus": {"coil": 1090, "type": "binary_sensor"},
        "hk3_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41092,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk3_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41093,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk3_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41100,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk3_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41094,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
        },
        "hk3_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41097,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk3_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41098,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk3_frostschutztemperatur": {
            "register": 41099,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
        },
        "hk3_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41106,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
        },
        "hk3_betriebsart": {
            "register": 48049,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk3_freigabe_externe_vorgabe": {
            "register": 48031,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk4": {
        "hk4_vorlauf_isttemperatur": {
            "register": 31121,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk4_vorlauf_solltemperatur": {
            "register": 31122,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk4_raumtemperatur": {
            "register": 31123,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk4_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41126,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk4_vorlauf_temperatur_externe_vorgabe": {
            "register": 48004,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
        },
        "hk4_pumpe_an_aus": {"coil": 1120, "type": "binary_sensor"},
        "hk4_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41122,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk4_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41123,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk4_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41130,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk4_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41124,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
        },
        "hk4_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41127,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk4_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41128,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
        },
        "hk4_frostschutztemperatur": {
            "register": 41129,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
        },
        "hk4_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41136,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
        },
        "hk4_betriebsart": {
            "register": 48050,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk4_freigabe_externe_vorgabe": {
            "register": 48032,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "austragung": {
        "fuellstand_im_pelletsbehaelter": {
            "register": 30022,
            "unit": "%",
            "scaling": 207,
            "decimals": 1,
            "type": "sensor",
        },
        "resetierbarer_kg_zaehler": {
            "register": 30082,
            "unit": "kg",
            "scaling": 1,
            "device_class": "weight",
            "type": "sensor",
        },
        "resetierbarer_t_zaehler": {
            "register": 30083,
            "unit": "t",
            "scaling": 1,
            "device_class": "weight",
            "type": "sensor",
        },
        "pelletverbrauch_gesamt": {
            "register": 30084,
            "unit": "t",
            "scaling": 10,
            "decimals": 1,
            "device_class": "weight",
            "state_class": "total",
            "type": "sensor",
        },
        "pelletlager_restbestand": {
            "register": 40320,
            "unit": "t",
            "scaling": 10,
            "decimals": 1,
            "min": 0,
            "max": 100,
            "type": "number",
        },
    },
    "puffer01": {
        "puffer_1_temperatur_oben": {
            "register": 32001,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_mitte": {
            "register": 32002,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_unten": {
            "register": 32003,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_fuehler_2": {
            "register": 32005,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_fuehler_3": {
            "register": 32006,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_pufferpumpen_ansteuerung": {
            "register": 32004,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_1_ladezustand": {
            "register": 32007,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_1_pufferpumpe_an_aus": {
            "register": 32004,
            "type": "binary_sensor_from_register",
        },
    },
    "puffer02": {
        "puffer_2_temperatur_oben": {
            "register": 32041,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_2_temperatur_mitte": {
            "register": 32042,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_2_temperatur_unten": {
            "register": 32043,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_2_pufferpumpen_ansteuerung": {
            "register": 32044,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_2_ladezustand": {
            "register": 32045,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_2_pufferpumpe_an_aus": {
            "register": 32044,
            "type": "binary_sensor_from_register",
        },
    },
    "puffer03": {
        "puffer_3_temperatur_oben": {
            "register": 32081,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_3_temperatur_mitte": {
            "register": 32082,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_3_temperatur_unten": {
            "register": 32083,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_3_pufferpumpen_ansteuerung": {
            "register": 32084,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_3_ladezustand": {
            "register": 32045,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_3_pufferpumpe_an_aus": {
            "register": 32084,
            "type": "binary_sensor_from_register",
        },
    },
    "puffer04": {
        "puffer_4_temperatur_oben": {
            "register": 32121,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_4_temperatur_mitte": {
            "register": 32122,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_4_temperatur_unten": {
            "register": 32123,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_4_pufferpumpen_ansteuerung": {
            "register": 32124,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_4_ladezustand": {
            "register": 32125,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_4_pufferpumpe_an_aus": {
            "register": 32124,
            "type": "binary_sensor_from_register",
        },
    },
    "zirkulationspumpe": {
        "ruecklauftemperatur_an_der_zirkulations_leitung": {
            "register": 30712,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "stoemungsschalter_an_der_brauchwasser_leitung": {
            "register": 30601,
            "unit": "",
            "scaling": 2,
            "type": "sensor",
        },
        "drehzahl_der_zirkulations_pumpe": {
            "register": 30711,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "zirkulationspumpe_an_aus": {
            "register": 30711,
            "type": "binary_sensor_from_register",
        },
    },
    "zweitkessel": {
        "start_zweitkessel": {
            "register": 40504,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "register_type": "holding",
        },
        "rueckschaltverzoegerung_zweitkessel_umschaltventil": {
            "register": 40512,
            "unit": "s",
            "scaling": 1,
            "register_type": "holding",
        },
        "temperatur_zweitkessel": {
            "register": 30501,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "umschaltventil_zweitkessel": {
            "register": 30504,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "zustand_brennerrelais": {
            "register": 30502,
            "unit": "",
            "scaling": 1,
            "type": "sensor",
        },
        "betriebsstunden_zweitkessel": {
            "register": 30503,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "minimaltemperatur_zweitkessel": {
            "register": 40507,
            "unit": "°C",
            "scaling": 2,
            "min": 20,
            "max": 95,
            "type": "number",
        },
        "temperaturdifferenz_zweitkessel_puffer": {
            "register": 40508,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 50,
            "type": "number",
        },
        "minimale_laufzeit_zweitkessel": {
            "register": 40505,
            "unit": "min",
            "scaling": 60,
            "min": 0,
            "max": 500,
            "type": "number",
        },
        "einschaltverzoegerung_zweitkessel": {
            "register": 40502,
            "unit": "min",
            "scaling": 60,
            "min": 0,
            "max": 500,
            "type": "number",
        },
    },
    "solarthermie": {
        "kollektor_ruecklauftemperatur": {
            "register": 32612,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "kollektor_vorlauftemperatur": {
            "register": 32613,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "kollektortemperatur": {
            "register": 32602,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "solarfuehler_puffer_oben": {
            "register": 32008,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "solarfuehler_puffer_unten": {
            "register": 30029,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "laufzeit_kollektorpumpe": {
            "register": 32603,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "aktuelle_leistung_des_solar_wmz": {
            "register": 32611,
            "unit": "kW",
            "scaling": 100,
            "decimals": 2,
            "device_class": "power",
            "type": "sensor",
        },
        "ansteuerung_kollektorpumpe": {
            "register": 32601,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "aktuelle_ansteuerung_der_kollektor_boiler_pumpe": {
            "register": 32623,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "solarthermie_dfl_sensor": {
            "register": 32610,
            "unit": "L/h",
            "scaling": 1,
            "device_class": "volume_flow_rate",
            "type": "sensor",
        },
        "solarthermie_tagesertrag": {
            "register": 32620,
            "unit": "kWh",
            "scaling": 1,
            "device_class": "energy",
            "type": "sensor",
        },
        "solarthermie_gesamtertrag": {
            "register": 32622,
            "unit": "kWh",
            "scaling": 1,
            "device_class": "energy",
            "state_class": "total",
            "type": "sensor",
        },
        "maximale_puffertemperatur_unten_bei_solarladung": {
            "register": 42603,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 90,
            "type": "number",
        },
        "kollektor_einschalt_differenz": {
            "register": 42601,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 50,
            "type": "number",
        },
        "kollektor_ausschalt_differenz": {
            "register": 42602,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 50,
            "type": "number",
        },
    },
}
